#!/usr/bin/env python3

from urllib.request import urlopen
from bs4 import BeautifulSoup
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input('Enter ')
html = urlopen(url, context=ctx).read()
soup = BeautifulSoup(html, 'html.parser')

tags = soup('a')
for t in tags:
    print('Tag: ', t)
    print('URL:', t.get('href',None))
    print('Content: ', t.contents[0])
    print('Attrs: ', t.attrs)
    
# Code: http://www.py4e.com/code3/urllink2.py
