#!/usr/bin/env python3

from urllib.request import urlopen
from bs4 import BeautifulSoup
import ssl

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input('Enter - ')
html = urlopen(url, context=ctx).read()
soup = BeautifulSoup(html, "html.parser")

lst = list()
tags = soup('span')
for tag in tags:
    lst.append(int(tag.contents[0]))
print('Count',len(lst))
print('Sum',sum(lst))

#url: http://py4e-data.dr-chuck.net/comments_1412627.html

